### ISSUE TITLE
NPE when running a document level pipeline

### ISSUE THREAD

**Issue by tseytlin** [DeepPhe/DeepPhe#13]
09 Nov 2015 15:14:43  INFO PittHeaderAnnotator - Starting Processing
09 Nov 2015 15:14:43  INFO PittHeaderAnnotator - Finished Processing
09 Nov 2015 15:14:43  INFO TokenizerAnnotatorPTB - process(JCas) in org.apache.ctakes.core.ae.TokenizerAnnotatorPTB
09 Nov 2015 15:14:43  INFO LvgAnnotator - process(JCas)
09 Nov 2015 15:14:43  INFO ContextDependentTokenizerAnnotator - process(JCas)
09 Nov 2015 15:14:43  INFO POSTagger - process(JCas)
09 Nov 2015 15:14:43  INFO Chunker -  process(JCas)
09 Nov 2015 15:14:43  INFO ChunkAdjuster -  process(JCas)
09 Nov 2015 15:14:43  INFO ChunkAdjuster -  process(JCas)
09 Nov 2015 15:14:43  INFO AbstractJCasTermAnnotator - Starting processing
09 Nov 2015 15:14:43  INFO AbstractJCasTermAnnotator - Finished processing
Nov 09, 2015 3:14:43 PM org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentProcess(407)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:391)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:296)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:567)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:309)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:195)
	at org.healthnlp.deepphe.uima.pipelines.DocumentSummarizerPipeline.runDocumentSummarizerPipeline(DocumentSummarizerPipeline.java:54)
	at org.healthnlp.deepphe.uima.pipelines.DocumentSummarizerPipeline.main(DocumentSummarizerPipeline.java:70)
Caused by: java.lang.NullPointerException
	at com.googlecode.clearnlp.morphology.EnglishMPAnalyzer.getNumber(EnglishMPAnalyzer.java:322)
	at com.googlecode.clearnlp.morphology.EnglishMPAnalyzer.getLemmaAux(EnglishMPAnalyzer.java:301)
	at com.googlecode.clearnlp.morphology.EnglishMPAnalyzer.getLemma(EnglishMPAnalyzer.java:273)
	at org.apache.ctakes.dependency.parser.ae.ClearNLPDependencyParserAE.process(ClearNLPDependencyParserAE.java:153)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:375)
	... 10 more

**Comment by seanfinan** [comment]
Hi Eugene,

Tim just turned his diligence toward this item.  I think that somebody over there had said that a sample note threw the same error.  Could you tell us which note that would be?

Thanks

**Comment by tseytlin** [comment]
Thank you for looking into this. It dies on the very first note (doc1.txt). It happened on the training set as well. Perhaps it is related to the format of the header?

**Comment by seanfinan** [comment]
I can run the ctakes pipeline.
I tried to update the latest and run using org.healthnlp.deepphe.uima.pipelines.DocumentSummarizerPipeline
However, I seem to be having a problem getting drools 5.5.0.Final from maven central.

Sean

**Comment by seanfinan** [comment]
I have grabbed the latest source and dependencies.  Both ctakes CancerPipelineRunner and DocumentSummarizerPipeline run through to completion on the 3 sample notes in [deepphe_root]/data/sample/docs/

**Comment by tseytlin** [comment]
Hmm, I tried both. Both failed, after git pull and  maven update. It is interesting that I no longer need to have cleartk jar file included.

Could it be a Linux only issue? Say something to do with Unix newlines vs Windows newlines?

**Comment by tmills** [comment]
I don't think so -- my attempt to replicate yesterday was on my linux machine. I believe Sean was using a windows machine. Maybe I'll try a completely fresh checkout today on my mac laptop and see what happens.

**Comment by tmills** [comment]
Clean checkout on mac runs on sample data without problems. I did run into some Jess errors running the full DeepPhePipeline but I think that might have some out of date code in it.
Just to be totally clear, you're running the DocumentSummarizerPipeline?

**Comment by tseytlin** [comment]
OK guys, that is totally my bad.  I should have cleared my Maven cache. After nuking several cleartk at .m2 folder, everything seems to wrk
