### ISSUE TITLE
Error running PhenotypeSummarizerPipeline

### ISSUE THREAD

**Issue by girishc** [DeepPhe/DeepPhe#14]
Message: No such slot summarizableId in template MAIN::TisStageFinding at token 'summarizableId'.
  Program text: ( defrule Stage0-1-1 "If document has pTis, pN0, pM0 then Stage 0 Breast Cancer" ( declare ( salience 1500 ) ) ?g <- ( Goal ( name ?name & : ( eq ?name "extract-stage" ) ) ( isActive 1 ) ) ( Patient ( id ?patientId ) ) ( TisStageFinding ( summarizableId  at line 1083 in file <eval pipe>.
	at jess.Jesp.error(Unknown Source)
	at jess.Jesp.a(Unknown Source)

**Comment by girishc** [comment]
This is running the old Jess based rule engine, which is now deprecated. After we have DROOLS completely integrated back here, this pipeline should be working again. I'll create a task for this in Trello
