### ISSUE TITLE
Null Features ?added? by one of the ?Temporal? Engines

### ISSUE THREAD

**Issue by seanfinan** [DeepPhe/DeepPhe#8]
When the cancer pipeline is run with the temporal engines, it seems that NULL features are added to the cas.  There are multiple "NULL Feature ..." errors in the log.

**Comment by tseytlin** [comment]
I presume that this is related to the bug I've encountered.
Here is the stacktrace, just in case
Oct 23, 2015 11:53:17 AM org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentProcess(407)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:391)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:296)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:567)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
    at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:309)
    at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:195)
    at org.healthnlp.deepphe.uima.pipelines.DocumentSummarizerPipeline.runDocumentSummarizerPipeline(DocumentSummarizerPipeline.java:54)
    at org.healthnlp.deepphe.uima.pipelines.DocumentSummarizerPipeline.main(DocumentSummarizerPipeline.java:70)
Caused by: java.lang.NullPointerException
    at com.googlecode.clearnlp.morphology.EnglishMPAnalyzer.getNumber(EnglishMPAnalyzer.java:322)
    at com.googlecode.clearnlp.morphology.EnglishMPAnalyzer.getLemmaAux(EnglishMPAnalyzer.java:301)
    at com.googlecode.clearnlp.morphology.EnglishMPAnalyzer.getLemma(EnglishMPAnalyzer.java:273)
    at org.apache.ctakes.dependency.parser.ae.ClearNLPDependencyParserAE.process(ClearNLPDependencyParserAE.java:153)
    at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:375)

**Comment by seanfinan** [comment]
Hi Eugene,

Sorry, I should have mentioned that I was testing the Git/Trello connection.
